# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoLibCliPoc < Formula
  desc ""
  homepage "https://github.com/TanmoySG/go-lib-cli-poc"
  version "1.2.2"

  on_macos do
    url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.2.2/go-lib-cli-poc_1.2.2_darwin_all.tar.gz"
    sha256 "04c519365b19bb0ff8538ccb0f7d94c2e719e981b41f4487fa795763867b1d05"

    def install
      bin.install "go-lib-cli-poc"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.2.2/go-lib-cli-poc_1.2.2_linux_arm64.tar.gz"
      sha256 "55745fd722f115f4e9b802831693c6026c755641245ad3e61ad968472c82c7e9"

      def install
        bin.install "go-lib-cli-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.2.2/go-lib-cli-poc_1.2.2_linux_amd64.tar.gz"
      sha256 "681a87e2ea39f64177c86edf99e6523c0a3fc19e1ab23e06cc7944f5aec1d69e"

      def install
        bin.install "go-lib-cli-poc"
      end
    end
  end
end
