# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoLibCliPoc < Formula
  desc ""
  homepage "https://github.com/TanmoySG/go-lib-cli-poc"
  version "1.1.11"

  on_macos do
    url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.11/go-lib-cli-poc_1.1.11_darwin_all.tar.gz"
    sha256 "67d3392e067c35cd8b18ab95904e7e7a72a5f102f8f14c76aae4aa63228ee196"

    def install
      bin.install "go-lib-cli-poc"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.11/go-lib-cli-poc_1.1.11_linux_amd64.tar.gz"
      sha256 "4a3e43ec1fdd5c2ea634aa3f1a86d96b1c3099961e2264c873c0abd75267a4d7"

      def install
        bin.install "go-lib-cli-poc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.11/go-lib-cli-poc_1.1.11_linux_arm64.tar.gz"
      sha256 "0ad32659f4d3b5b83204e9d6ddc8078c21a989e8487f09070dbcde8e201f1f51"

      def install
        bin.install "go-lib-cli-poc"
      end
    end
  end
end
