# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoLibCliPoc < Formula
  desc ""
  homepage "https://github.com/TanmoySG/go-lib-cli-poc"
  version "1.1.12"

  on_macos do
    url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.12/go-lib-cli-poc_1.1.12_darwin_all.tar.gz"
    sha256 "ec077dd30d6df5a58cf4383f87ce8d064087dcb94faaea4c261be91af2118f79"

    def install
      bin.install "go-lib-cli-poc"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.12/go-lib-cli-poc_1.1.12_linux_arm64.tar.gz"
      sha256 "1f1119adacd3cdc6260315d2effa9a0f746bf379327ddb841166cb12e508bd5e"

      def install
        bin.install "mathctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.12/go-lib-cli-poc_1.1.12_linux_amd64.tar.gz"
      sha256 "cae557e1378cdfe1080a4aaf6096c31cc854c726adcfde8f73e53988815aa652"

      def install
        bin.install "mathctl"
      end
    end
  end
end
