# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mathctl < Formula
  desc ""
  homepage "https://github.com/TanmoySG/go-lib-cli-poc"
  version "1.1.14"

  on_macos do
    url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.14/go-lib-cli-poc_1.1.14_darwin_all.tar.gz"
    sha256 "0b45e2c56936cb1702dca96aea2e4695104c07a043f1d7c2a3c3fbf0d67709a5"

    def install
      bin.install "go-lib-cli-poc"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.14/go-lib-cli-poc_1.1.14_linux_arm64.tar.gz"
      sha256 "7f04c4ae76fe27efb77d90f19a4a972a84ac901e3b3990c0c9b7a4be102d1365"

      def install
        bin.install "mathctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.14/go-lib-cli-poc_1.1.14_linux_amd64.tar.gz"
      sha256 "52d1bc6b97eac60254ac9e05ffc8aaa1ec5ee9f32980783e34720d813a11b718"

      def install
        bin.install "mathctl"
      end
    end
  end
end
