# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mathctl < Formula
  desc ""
  homepage "https://github.com/TanmoySG/go-lib-cli-poc"
  version "1.1.13"

  on_macos do
    url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.13/go-lib-cli-poc_1.1.13_darwin_all.tar.gz"
    sha256 "1b35a6678bf1b5f40fc87be5224c5008babc376cc9aade4b872a3dfc253e4213"

    def install
      bin.install "go-lib-cli-poc"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.13/go-lib-cli-poc_1.1.13_linux_arm64.tar.gz"
      sha256 "41e25db1b13dadf3d92b09418473ead750bcfbdb099dd1e61735b58aff9cae89"

      def install
        bin.install "mathctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.13/go-lib-cli-poc_1.1.13_linux_amd64.tar.gz"
      sha256 "e5c601b60e84b43d3bc4232f3bd737228c8aa83f5e574ce48fc307f36bd066b8"

      def install
        bin.install "mathctl"
      end
    end
  end
end
