# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mathctl < Formula
  desc ""
  homepage "https://github.com/TanmoySG/go-lib-cli-poc"
  version "1.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.6/go-lib-cli-poc_Darwin_arm64.tar.gz"
      sha256 "02fff222e92f897d79adff21a1c03b19500cc96f76076013179d793f6e623e7f"

      def install
        bin.install "go-lib-cli-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.6/go-lib-cli-poc_Darwin_x86_64.tar.gz"
      sha256 "60498fe3be4e2ba5ae90b2e6d68b88445c9919558749b4e2e3bb07f748e8bea4"

      def install
        bin.install "go-lib-cli-poc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.6/go-lib-cli-poc_Linux_x86_64.tar.gz"
      sha256 "f57316de238b8e6b71f31c16ff76644eb3eeb66ead3292b9ecd17f487b390a19"

      def install
        bin.install "go-lib-cli-poc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/go-lib-cli-poc/releases/download/v1.1.6/go-lib-cli-poc_Linux_arm64.tar.gz"
      sha256 "6a9898fae3be1e35ac38e7fe4455647f96c14e63747f02d769a6dd31a9efe507"

      def install
        bin.install "go-lib-cli-poc"
      end
    end
  end
end
