# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wdbcli < Formula
  desc ""
  homepage "https://github.com/TanmoySG/wdbcli"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/wdbcli/releases/download/v2.0.1/wdbcli_2.0.1_darwin_amd64.tar.gz"
      sha256 "b00bad30a84529d73df7bb054a772b15a2ff67c90afea87cc53940083a72efb2"

      def install
        bin.install "wdbcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TanmoySG/wdbcli/releases/download/v2.0.1/wdbcli_2.0.1_darwin_arm64.tar.gz"
      sha256 "d6a4d84e6739b690bdde65b63f2bfb5a1c06ccf2231f5f1520ee6c855b5c2698"

      def install
        bin.install "wdbcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/wdbcli/releases/download/v2.0.1/wdbcli_2.0.1_linux_armv6.tar.gz"
      sha256 "5253e1c1ac8aeae105c4ad3c4161cee4296fff5e5ed91ad23cfee32622d14f8f"

      def install
        bin.install "wdbcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/wdbcli/releases/download/v2.0.1/wdbcli_2.0.1_linux_amd64.tar.gz"
      sha256 "003ceba090c797a3a6e5d1ad70b1dcbeaa26a7b32f0ce7ae8f15cacf64798e34"

      def install
        bin.install "wdbcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/wdbcli/releases/download/v2.0.1/wdbcli_2.0.1_linux_arm64.tar.gz"
      sha256 "4a1398c090382dfc351d24836c156646645d7e09121dcf7e89dea5a5348cd906"

      def install
        bin.install "wdbcli"
      end
    end
  end
end
