# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wdbctl < Formula
  desc ""
  homepage "https://github.com/TanmoySG/wunderDB"
  version "2.0.0-beta"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TanmoySG/wunderDB/releases/download/v2.0.0-beta/wdbctl_2.0.0-beta_darwin_arm64.tar.gz"
      sha256 "17d1f51c59da52296b3157761d2b3eadb2b538bd4332e7ec1f3a19fe3d382297"

      def install
        bin.install "wdbctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/wunderDB/releases/download/v2.0.0-beta/wdbctl_2.0.0-beta_darwin_amd64.tar.gz"
      sha256 "b28c2f2209a4d251709aa4865bc16726d996ee6f8e447610115be43c08186daa"

      def install
        bin.install "wdbctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/wunderDB/releases/download/v2.0.0-beta/wdbctl_2.0.0-beta_linux_arm.tar.gz"
      sha256 "f5be80ee792bb79dbaa9459ebf3b468b8b38bb7c233c610bc3ba08f1ce0837a6"

      def install
        bin.install "wdbctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TanmoySG/wunderDB/releases/download/v2.0.0-beta/wdbctl_2.0.0-beta_linux_arm64.tar.gz"
      sha256 "272025f6b9bbe70b44d7c167ca6df4830bf6391ddfb6211e96e46ba704ca513e"

      def install
        bin.install "wdbctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TanmoySG/wunderDB/releases/download/v2.0.0-beta/wdbctl_2.0.0-beta_linux_amd64.tar.gz"
      sha256 "a875b678e99de394f20b95e83eb0b58cbb26e44f6b7e22d3d17b8c843471defe"

      def install
        bin.install "wdbctl"
      end
    end
  end
end
